### ISSUE TITLE
gr discover failes on Windows

### ISSUE THREAD

**Issue by ddcruver** [mixu/gr#10]
Windows 7
Installed Node.JS and NPM installed with Chocolatey by nodejs.install (Which uses the official installer)
Running in Node.js Command Prompt
>gr discover

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

**Comment by nichtich** [comment]
Have you tried `git tag discover`? This issue could be a duplicate of #18

**Comment by mixu** [comment]
I changed the routing in master to make `gr discover` call `gr tag discover` since this seems to be a be somewhat common issue when getting started with `gr`.
