### ISSUE TITLE
nodejs instead of node

### ISSUE THREAD

**Issue by imr-ctu** [mixu/gr#15]
On Ubuntu 14.04, gr doesn't work out of the box because the crash-bang line uses `node` instead of `nodejs`.
`#!/usr/bin/env node` should be `#!/usr/bin/env nodejs`

The workaround is to install  the `nodejs-legacy` package.

I don't know how it is with other distro.

**Comment by mixu** [comment]
I think this is a universal problem with Ubuntu/Debian, see:

https://github.com/joyent/node/issues/3911
https://lists.debian.org/debian-devel-announce/2012/07/msg00002.html

As former BDFL isaacs said, the canonical executable name is "node":

https://github.com/joyent/node/issues/4772

I haven't seen any other packages on npm use `nodejs` in their env line, so I'm afraid I'm not going to do it either.
