### ISSUE TITLE
"gr" collides with an alias in the zsh git plugin

### ISSUE THREAD

**Issue by tleach** [mixu/gr#16]
Firstly - this is a great looking project which I'm excited to try out. 

One initial stumbling block I've encountered is that the `gr` command collides with the [`gr` alias in the zsh git plugin](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh#L35). 

Obviously if you don't use this plugin you don't really care, but at my company at least it's widely used.

Would be cool if gr shipped with a couple of aliases (`gitrun`, `git-run`, `grun` maybe?) to allow one to work around the name collision. 

Let me know if this is of interest and I'll submit a pull request.

**Comment by tleach** [comment]
Actually, on second thoughts it might just be simpler to run `unalias gr` to remove the zsh alias.

**Comment by floriantraber** [comment]
@mixu can we add a note in the docs for this? They already mention zsh, so I naturally felt that it should work out of the box.
