### ISSUE TITLE
`gr discover` error

### ISSUE THREAD

**Issue by Zearin** [mixu/gr#18]
Ran in my home directory:

```
$ gr discover

in ./

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn discover ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

My info:

* OS X 10.9 (Mavericks)
* `node --version`: v0.12.0
* `npm --version`: 2.6.0
* `git --version`: git version 2.3.0

**Comment by mixu** [comment]
The `discover` command is actually `gr tag discover`, but this brings up an important point - error messages should be made more user-friendly. I'll leave this open for the next time I am working on gr.

**Comment by mixu** [comment]
I changed the routing in master to make `gr discover` call `gr tag discover` since this seems to be a be somewhat common issue when getting started with `gr`.
