### ISSUE TITLE
Update documentation to state where tags are stored?

### ISSUE THREAD

**Issue by clauswilke** [mixu/gr#30]
Hello,

this looks like a great project. I was thinking I had to write something like this myself, now I don't have to.

I have a minor request for the documentation: Could you mention where tags are actually stored? Does gr have a config file where it keeps all that information, or is it somehow added to each git repository?

Thanks!

**Comment by mixu** [comment]
sure - the config is stored in `~/.grconfig.json`. For example:

```json
{
 "tags": {
  "books": [
    "/home/m/mnt/css-book" 
  ]
}
```

All plugins can share the config, e.g. https://github.com/mixu/gr/blob/master/plugins/tag.js#L29

If you have some time to write up a PR against the readme, I'd be happy to merge it - alternatively I'll update it some time later.

**Comment by clauswilke** [comment]
Pull request done, as requested.

**Comment by mixu** [comment]
Awesome, thanks!
