### ISSUE TITLE
gr @tag status makes a redundant call to git status

### ISSUE THREAD

**Issue by coderjoe** [mixu/gr#34]
The status command currently executes two child processes to fetch the status of a repository. I believe this could be reduced to one call to `git status --branch --porcelain`.

I'll prepare a pull request for your review, my only worry is that I can't seem to run the full test suite on the machine I have access to at the moment.

**Comment by mixu** [comment]
cool, would be happy to merge this. Let me know if you have trouble resolving the test issues, `make test` seems to work on my OSX/Node 0.12.6 setup.

**Comment by coderjoe** [comment]
I think I've got the test suite working locally. The referenced PR passes all tests on my local machine in node 0.12.6 and 4.0.0. I can test in more versions if you'd prefer, but that will have to wait until tomorrow.

**Comment by mixu** [comment]
awesome! published as `v0.4.1`, thanks for fixing this issue!
