### ISSUE TITLE
http://mixu.net/gr/ is using the old '#' syntax

### ISSUE THREAD

**Issue by nwinkler** [mixu/gr#39]
The documentation on http://mixu.net/gr/ is still using the old '#' syntax for tags, not the new one.

This threw me off, since I was looking at the examples there and couldn't figure out how this worked in v0.4.1.

**Comment by michaek** [comment]
@mixu I couldn't find a repo for the documentation site. If there is one, I'll make a pull request to update this.

**Comment by mixu** [comment]
The repo HTML was finally updated - this has been a bit of a persistent issue (sites going out of sync), so I wrote a thing that listens on Github push events, runs an AWS Lambda and rebuilds the site on S3 (where it lives). I'll open source it once I iron out the bugs, but automatically rebuilding the site will definitely help keep it in sync from now on...
