### ISSUE TITLE
avoid @tag and use just word or tag1/tag2/tag3

### ISSUE THREAD

**Issue by epcim** [mixu/gr#45]
Couple of issues here:

- it's nice in configs, listing, during the discover (all the visual) but for writing it each time point less.
- fish shell, while defining an alias by function, cant send "@" as that way is used by fish to "some" array object.

why not just:
```
gr work git status
gr work/github git status     # and treat it as $1.split('/') ?
```

Regarding aliases for shell, ie the fish shell example, one would like to use sth like following code to address command on specific set of repositories:
```
function grs
   # you cant pass @ without \ or using ''
   gr @$argv[1..-1] git status
``` 
however, if "gr" would work only with the set of repositories under current $PWD this would not be almost necessary.

**Comment by mixu** [comment]
yeah `@` used to be `#` which was even more problematic. You can use `-t` as an alternative syntax e.g `gr -t work -t play` so I think it's not too bad. I would like to avoid the ambiguity between words/tags and commands, e.g. is `work/github` a tag or is it an invocation of a command?
