### ISSUE TITLE
Feature request - Export & import of repo collections

### ISSUE THREAD

**Issue by schlessera** [mixu/gr#47]
Hey @mixu , thank for the great `gr`, it is very useful!

I would really love to see an export & import feature so that developers can share a collection of repos.

I imagine it could work something like this:
1. Developer A has a folder full of repos in his `~/dev/company` folder.
2. He runs `gr export ~/dev/company`.
3. `gr` creates a list of relative folder names, corresponding git repo URIs, and corresponding tags for each of the subfolders.
4. Developer A sends that file (maybe JSON named `gr-export.json`?) to Developer B.
5. Developer B creates a new folder `~/company-dev`.
6. Developer B runs the command `gr import gr-export.json ~/company-dev`.
7. `gr` now creates each of the subfolders in this new location.
8. Inside of each folder, `gr` clones the corresponding repo.
9. `gr` tags the folders with the same tags they had at Developer A's location.

So, this lets developers share a completely configured folder hierarchy. To onboard a new developer, he simply needs to `gr import` the latest company export.

**Comment by mixu** [comment]
:+1: this could be written as a plugin and would be great! happy to accept a PR

**Comment by timja-kainos** [comment]
@schlessera If you're still interested in this would you like to try out #59 ?

**Comment by schlessera** [comment]
@timja-kainos I am not using `gr` with the project I am currently working on.
As soon as I get a new opportunity to work with `gr`, I will make sure to test this, but I cannot tell you when that will be...

**Comment by mixu** [comment]
implemented in #59
