### ISSUE TITLE
gr discover output file location?

### ISSUE THREAD

**Issue by someshSandbox** [mixu/gr#52]
After I run "gr discover ~/git-repos" , I am prompted with a list of repos. I add the appropriate tag @xyz. The default location of the file is "/tmp/gr-repos-tmp.txt". How are these tags applied to the repo. git discover doesn't automatically update my .grconfig.json file. Can I specify the location of gr-repos-tmp.txt  in my  .grconfig.json ?

**Comment by mixu** [comment]
weird. basically that file is read after it has been saved, and then parsed and discarded so it's not part of the actual config - it just gets translated into tag changes and then thrown out.

You can do the same thing manually via `gr tag add sometag /path/to/dir` but its a bit more work.
