### ISSUE TITLE
how to work with multiple tags?

### ISSUE THREAD

**Issue by zhaocai** [mixu/gr#53]
For example, I want to `git grep` repos tagged with both `JavaScript` and `lib`. How do I do that?

**Comment by mixu** [comment]
as mentioned in the readme, you can pass as many targets as you want. `gr @foo @bar git --no-pager grep "js"`

**Comment by zhaocai** [comment]
@mixu

1. `@` is not working in some shells (PowerShell for example). `gr -t foo -t bar git --no-pager grep "js"` is not working as `-t bar git --no-pager grep "js"` is parsed as the command to execute.

2. What I want is not to work with repos tagged with `@foo` **or** `@bar` but `@foo` **and** `@bar`.

**Comment by andreineculau** [comment]
> What I want is not to work with repos tagged with @foo or @bar but @foo and @bar.

@mixu any update on this? I'm looking for the same thing
