### ISSUE TITLE
Doesn't work on submodules.

### ISSUE THREAD

**Issue by spacemoose** [mixu/gr#54]
If foo/ is a git repo containing a submodule bar/, and I try to execute 'status' on bar, I get:  "Missing .git directory".  Any chance this can generalized to work for submodules?

**Comment by cojomojo** [comment]
I too have found myself wishing this would work with submodules. I believe it can be made to work pretty easily.  All that seemingly needs to change is this function. Just need to check if the parent directory has a .gitmodules file, and a .git directory. I will try and submit a PR with these changes.

```
  git: function(req) {
    var stat;
    try {
      stat = fs.statSync(req.path + '/.git/');
      if (stat.isDirectory()) {
        return true;
      }
    } catch (e) { }
    if (req.format === 'human') {
      console.log('Skipped ' + req.path + ' as it does not have a .git subdirectory.');
    }
    return false;
  },
```

**Comment by mixu** [comment]
merged & published

**Comment by spacemoose** [comment]
Hey, super.  Thanks very much for that.

**Comment by bimlas** [comment]
It works if the submodule is the first child of the root directory but not works if the submodule is in `foo/more/than/one/level/bar`. I don't speak Java, but I know that some kind of globbing should do the trick [here](https://github.com/cojomojo/gr/blob/master/lib/command-requirements.js#L16), or a loop like:

```js
      while !empty(req.path) {
        var parentPath = path.dirname(req.path);
        try {
          stat = fs.statSync(parentPath + '/.gitmodules');
          if (!stat.isFile()) {
            var req.path = removeLastPart(req.path);
          }
        } catch (e) { }
      }
      return empty(req.path) ? false : true;
```

**Comment by bimlas** [comment]
Another option: if `.git` is a file instead of a directory (so it's a submodule), then read the contents, for example:

```
gitdir: ../../../../.git/more/than/one/level/bar
```

If it contains `gitdir:` than it's a submodule.

**Comment by bimlas** [comment]
Please help me in #65

**Comment by bimlas** [comment]
Just finished #65, please test it.
