### ISSUE TITLE
The current method for detecting submodules does not work in all cases.

### ISSUE THREAD

**Issue by cojomojo** [mixu/gr#66]
Say the .git directory is in `foo/`, and the submodule path is  `foo/bar/submodule`... then the way we are currently checking for a submodule directory fails as mentioned in #65. 

Also, I have come across an issue on Windows 7 where the current method fails even when the submodule path is `foo/submodule`. 

Overall, as @bimlas mentions in #54 / #65, it would be much better if we check for git directories by executing a variant of the command 'git rev-parse`.  Specifically, the best command to use is `git rev-parse --is-inside-git-dir', which returns true if the directory is the working tree, false if it is in the .git tree (i.e. untracked, but in a place where git commands are still valid), and throws a fatal error if it is not a git directory.

**Comment by mixu** [comment]
I have no strong opinions on `git rev-parse --show-prefix` vs `git rev-parse --is-inside-git-dir` since my use case tends to be pretty simple, happy to revisit this but closing for now since #65 landed
