### ISSUE TITLE
`discover` should be able to take a path

### ISSUE THREAD

**Issue by alexgorbatchev** [mixu/gr#7]
I don't think it's useful to traverse all folders for a user, it would be much better if one could specify project path to easily upstart a project.

**Comment by nasht00** [comment]
+1

**Comment by coderjoe** [comment]
I'd also love to be able to provide a path to discover. If nobody on the project objects I'd be happy to take a stab at the path argument. Would people want discover to take a single argument, space separated list of arguments, something else?

**Comment by mixu** [comment]
fixed by @coderjoe 's PR
